grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
model_selection:
  module_0:
    class: AdaBoostClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 300
      learning_rate: 0.9
      algorithm: SAMME.R
    search_param_grid:
      n_estimators:
      - 50
      - 150
      - 300
      learning_rate:
      - 0.05
      - 0.1
      - 0.9
      algorithm:
      - SAMME
      - SAMME.R

      
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 250
      min_samples_split: 2
      min_samples_leaf: 1
      max_features: 4
      max_depth: 1
      criterion: gini
    search_param_grid:
      n_estimators:
      - 100
      - 250
      min_samples_split:
      - 2
      - 6
      min_samples_leaf:
      - 1
      - 3
      max_features:
      - 4
      - 10
      max_depth:
      - 1
      - 10
      criterion:
      - gini
      - entropy

     